version: '3'
services:

  # ----------------- #
  # Apache Spark      #
  # ----------------- #
  spark:
    container_name: spark-master  
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
  spark-worker:
    container_name: spark-worker
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    volumes:
      - ./data:/data
      - ./src:/src 
  # ----------------- #
  # Apache Zookeeper  #
  # ----------------- #
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  # ----------------- #
  #   apache Kafka    #
  # ----------------- #
  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:2.0
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  # ----------------- #
  #       Mysql       #
  # ----------------- #
  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.0
    ports:
     - 3307:3307
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  # ----------------- #
  #     debezium      #
  # ----------------- #
  connect:
    container_name: debezium
    image: quay.io/debezium/connect:2.0
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1 
     - CONFIG_STORAGE_TOPIC=my_connect_configs 
     - OFFSET_STORAGE_TOPIC=my_connect_offsets 
     - STATUS_STORAGE_TOPIC=my_connect_statuses 